default: &default
  adapter: postgresql
  pool: 10
  timeout: 5000
  encoding: unicode

development:
  <<: *default
  host: localhost
  user: fuzzybot
  database: fuzzybot
  password: fuzzybot

production:
  <<: *default
  host: db
  user: postgres
  database: postgres
  password: postgres
